CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_featured ON products(featured);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);
CREATE INDEX IF NOT EXISTS idx_products_active_display_created ON products(active, display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_active_featured_display ON products(active, featured, display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_active_size ON product_variants(product_id, active, size_ml);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_active_price ON product_variants(product_id, active, price_ars_cents);
CREATE INDEX IF NOT EXISTS idx_product_images_product_sort ON product_images(product_id, is_primary DESC, sort_order ASC);
CREATE INDEX IF NOT EXISTS idx_orders_external_reference ON orders(external_reference);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_created_at ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_events_mp_payment_id ON payment_events(mp_payment_id);
CREATE INDEX IF NOT EXISTS idx_discount_codes_code ON discount_codes(code);
CREATE INDEX IF NOT EXISTS idx_discount_codes_active_code ON discount_codes(active, code);
CREATE INDEX IF NOT EXISTS idx_contact_messages_read_created_at ON contact_messages(read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shipping_zones_active_cost ON shipping_zones(active, base_cost_cents);
